name: Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer Black et Ruff
        run: |
          pip install black==23.11.0 ruff

      - name: Vérifier le format avec Black
        run: black --check .

      - name: Vérifier le style avec Ruff
        run: ruff check .
